<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{
	public function setUp()
    {
        $this->hasMutator('password', 'md5Passwrd');
    }

    public function md5Passwrd($value)
    {
        $this->_set('password', md5($value));
    }
}